// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package simple

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func DecodeSimple(in *jlexer.Lexer, out *StatsRequestJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "urls":
			out.URLs = int64(in.Int64())
		case "users":
			out.Users = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func EncodeSimple(out *jwriter.Writer, in StatsRequestJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"urls\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.URLs))
	}
	{
		const prefix string = ",\"users\":"
		out.RawString(prefix)
		out.Int64(int64(in.Users))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatsRequestJSON) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	EncodeSimple(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatsRequestJSON) MarshalEasyJSON(w *jwriter.Writer) {
	EncodeSimple(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatsRequestJSON) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	DecodeSimple(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatsRequestJSON) UnmarshalEasyJSON(l *jlexer.Lexer) {
	DecodeSimple(l, v)
}
func DecodeSimple1(in *jlexer.Lexer, out *ResponseJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "result":
			out.Result = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func EncodeSimple1(out *jwriter.Writer, in ResponseJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		out.String(string(in.Result))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseJSON) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	EncodeSimple1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseJSON) MarshalEasyJSON(w *jwriter.Writer) {
	EncodeSimple1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseJSON) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	DecodeSimple1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseJSON) UnmarshalEasyJSON(l *jlexer.Lexer) {
	DecodeSimple1(l, v)
}
func DecodeSimple2(in *jlexer.Lexer, out *RequestJSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "url":
			out.URL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func EncodeSimple2(out *jwriter.Writer, in RequestJSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestJSON) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	EncodeSimple2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestJSON) MarshalEasyJSON(w *jwriter.Writer) {
	EncodeSimple2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestJSON) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	DecodeSimple2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestJSON) UnmarshalEasyJSON(l *jlexer.Lexer) {
	DecodeSimple2(l, v)
}
