definitions:
  ItemRequest:
    properties:
      correlation_id:
        type: string
      original_url:
        type: string
    type: object
  ItemResponse:
    properties:
      correlation_id:
        type: string
      short_url:
        type: string
    type: object
  RequestJSON:
    properties:
      url:
        type: string
    type: object
  ResponseJSON:
    properties:
      result:
        type: string
    type: object
  StatsRequestJSON:
    properties:
      urls:
        type: integer
      users:
        type: integer
    type: object
  internal_app_handler.ErrorResponse:
    properties:
      error:
        example: error message
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    post:
      consumes:
      - text/plain
      description: Создает короткую версию переданного URL
      parameters:
      - description: Оригинальный URL
        in: body
        name: url
        required: true
        schema:
          type: string
      produces:
      - text/plain
      responses:
        "201":
          description: Сокращенный URL
          schema:
            type: string
        "400":
          description: Неверный запрос
          schema:
            type: string
        "409":
          description: URL уже существует
          schema:
            type: string
      summary: Сократить URL (текстовый формат)
  /{id}:
    get:
      description: Перенаправляет на оригинальный URL по короткому идентификатору
      parameters:
      - description: Короткий идентификатор URL
        in: path
        name: id
        required: true
        type: string
      responses:
        "307":
          description: Перенаправление на оригинальный URL
        "404":
          description: URL не найден
          schema:
            type: string
        "410":
          description: URL удален
          schema:
            type: string
      summary: Перенаправить по короткому URL
  /api/internal/stats:
    get:
      description: Возвращает количество ссылок и пользователей в приложении
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/StatsRequestJSON'
      summary: Получить статистику
  /api/shorten:
    post:
      consumes:
      - application/json
      description: Создает короткую версию переданного URL
      parameters:
      - description: Запрос с URL
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/RequestJSON'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/ResponseJSON'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/internal_app_handler.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/ResponseJSON'
      summary: Сократить URL (JSON формат)
  /api/shorten/batch:
    post:
      consumes:
      - application/json
      description: Создает несколько коротких URL за один запрос
      parameters:
      - description: Массив URL для сокращения
        in: body
        name: urls
        required: true
        schema:
          items:
            items:
              $ref: '#/definitions/ItemRequest'
            type: array
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              items:
                $ref: '#/definitions/ItemResponse'
              type: array
            type: array
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/internal_app_handler.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/internal_app_handler.ErrorResponse'
      summary: Пакетное создание коротких URL
  /api/user/urls:
    delete:
      consumes:
      - application/json
      description: Помечает указанные URL как удаленные (асинхронно)
      parameters:
      - description: Массив коротких URL для удаления
        in: body
        name: urls
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "202":
          description: Запрос принят в обработку
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/internal_app_handler.ErrorResponse'
        "401":
          description: Пользователь не авторизован
          schema:
            type: string
      summary: Удалить URL пользователя
    get:
      description: Возвращает все сокращенные URL текущего пользователя
      produces:
      - application/json
      responses:
        "200":
          description: Массив URL пользователя
          schema:
            items:
              additionalProperties:
                type: string
              type: object
            type: array
        "204":
          description: Нет сохраненных URL
      summary: Получить URL пользователя
  /ping:
    get:
      description: Проверяет доступность базы данных
      responses:
        "200":
          description: База данных доступна
        "500":
          description: Ошибка соединения с БД
          schema:
            type: string
      summary: Проверить соединение с БД
swagger: "2.0"
