// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package batch

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func DecodeBatch(in *jlexer.Lexer, out *ItemResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "correlation_id":
			out.CorrelationID = string(in.String())
		case "short_url":
			out.ShortURL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func EncodeBatch(out *jwriter.Writer, in ItemResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"correlation_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.CorrelationID))
	}
	{
		const prefix string = ",\"short_url\":"
		out.RawString(prefix)
		out.String(string(in.ShortURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ItemResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	EncodeBatch(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ItemResponse) MarshalEasyJSON(w *jwriter.Writer) {
	EncodeBatch(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ItemResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	DecodeBatch(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ItemResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	DecodeBatch(l, v)
}
func DecodeBatch1(in *jlexer.Lexer, out *ItemRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "correlation_id":
			out.CorrelationID = string(in.String())
		case "original_url":
			out.OriginalURL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func EncodeBatch1(out *jwriter.Writer, in ItemRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"correlation_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.CorrelationID))
	}
	{
		const prefix string = ",\"original_url\":"
		out.RawString(prefix)
		out.String(string(in.OriginalURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ItemRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	EncodeBatch1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ItemRequest) MarshalEasyJSON(w *jwriter.Writer) {
	EncodeBatch1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ItemRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	DecodeBatch1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ItemRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	DecodeBatch1(l, v)
}
func DecodeBatch2(in *jlexer.Lexer, out *BatchResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(BatchResponse, 0, 2)
			} else {
				*out = BatchResponse{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 ItemResponse
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func EncodeBatch2(out *jwriter.Writer, in BatchResponse) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v BatchResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	EncodeBatch2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BatchResponse) MarshalEasyJSON(w *jwriter.Writer) {
	EncodeBatch2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BatchResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	DecodeBatch2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BatchResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	DecodeBatch2(l, v)
}
func DecodeBatch3(in *jlexer.Lexer, out *BatchRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(BatchRequest, 0, 2)
			} else {
				*out = BatchRequest{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v4 ItemRequest
			(v4).UnmarshalEasyJSON(in)
			*out = append(*out, v4)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func EncodeBatch3(out *jwriter.Writer, in BatchRequest) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v5, v6 := range in {
			if v5 > 0 {
				out.RawByte(',')
			}
			(v6).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v BatchRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	EncodeBatch3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BatchRequest) MarshalEasyJSON(w *jwriter.Writer) {
	EncodeBatch3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BatchRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	DecodeBatch3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BatchRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	DecodeBatch3(l, v)
}
